# Generated by Django 4.1.5 on 2023-01-30 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TickerAnswer",
            new_name="TicketAnswer",
        ),
        migrations.RemoveField(
            model_name="account",
            name="email_unique_code",
        ),
    ]
